### ISSUE TITLE
occasional garbage in wpiutil logging

### ISSUE THREAD

**Issue by nightpool** [wpilibsuite/wpiutil#35]
found when testing shuffleboard without a NT server running

![image](https://user-images.githubusercontent.com/233815/30517216-62997a16-9b26-11e7-99cd-07a6e79ad2a9.png)

**Comment by nightpool** [comment]
Not sure if this just threading issues or something else. Can anybody reproduce this standalone? (i.e. without javafx) 

here's a log snippet: https://gist.github.com/nightpool/7a2f64cbc8990568aecd822d84855d64

**Comment by PeterJohnson** [comment]
Is this with the latest HEAD?  It's very confusing as it's not even the filename part.  Are you hooking the logger or is this the default logger?

**Comment by PeterJohnson** [comment]
This can't be a bug in wpiutil, as it's not responsible for adding the file/line.  https://github.com/wpilibsuite/ntcore/commit/12b2efa489bdd0beaae2cf8499a8386602c94577 could cause this behavior as it separately prints the file/line/etc, but this was fixed in https://github.com/wpilibsuite/ntcore/commit/5ab20bb27c9720304f3ca2a6d4eecd918e27555e
